/* ============================================
   ESQUEMA BASE
   ============================================ */
-- Opcional: USE TuBaseDeDatos;
-- CREATE SCHEMA app AUTHORIZATION dbo;
-- En este script uso dbo por simplicidad.

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

/* ============================================
   CATÁLOGOS (TINYINT)
   ============================================ */
CREATE TABLE AREAS (
  ID_AREA   TINYINT NOT NULL, -- 1 Trabajo, 2 Empresa, 3 Personal
  NOMBRE    VARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
  CONSTRAINT PK_AREAS PRIMARY KEY (ID_AREA));

INSERT INTO AREAS(ID_AREA,NOMBRE) VALUES (1,'Trabajo'),(2,'Personal');

CREATE TABLE EISENHOWER (
  ID_EISENHOWER TINYINT     NOT NULL CONSTRAINT PK_EISENHOWER PRIMARY KEY, -- 1 IU, 2 InU, 3 nIU, 4 ni
  CODIGO        VARCHAR(4)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  NOMBRE        VARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL);
INSERT INTO EISENHOWER VALUES
(1,'IU', N'Importante & Urgente'),
(2,'InU',N'Importante & no Urgente'),
(3,'nIU',N'no Importante & Urgente'),
(4,'ni', N'no Importante & no Urgente');

CREATE TABLE MODO_ROLLOVER (
  ID_MODO_ROLLOVER   TINYINT     NOT NULL CONSTRAINT PK_MODO_ROLLOVER PRIMARY KEY, -- 1 Acumulativo, 2 Balanceado, 3 Estricto
  NOMBRE VARCHAR(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL);
INSERT INTO MODO_ROLLOVER VALUES
(1,'Acumulativo'),(2,'Balanceado'),(3,'Estricto');

CREATE TABLE TIPO_EVENTO (
  ID_TIPO_EVENTO TINYINT NOT NULL CONSTRAINT PK_TIPO_EVENTO PRIMARY KEY, -- 1 Cumpleaños, 2 Vacaciones, 3 Junta, 4 Social, 5 Cobro, 6 Otro
  NOMBRE         VARCHAR(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL);
INSERT INTO TIPO_EVENTO VALUES (1,'Cumpleaños'),(2,'Vacaciones'),(3,'Junta'),(4,'Evento social'),(5,'Cobro');

CREATE TABLE TIPO_MOVTO (
  ID_TIPO_MOVTO TINYINT NOT NULL CONSTRAINT PK_TIPO_MOVTO PRIMARY KEY, -- 1 Cobro, 2 Pago
  NOMBRE        VARCHAR(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL);
INSERT INTO TIPO_MOVTO VALUES (1,'Cobro'),(2,'Pago');

CREATE TABLE STATUS_MOVTO (
  ID_STATUS_MOVTO    TINYINT NOT NULL CONSTRAINT PK_STATUS_MOVTO PRIMARY KEY, -- 1 Pendiente, 2 Realizado, 3 Vencido, 4 Cancelado
  NOMBRE VARCHAR(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL);
INSERT INTO STATUS_MOVTO VALUES
(1,'Pendiente'),(2,'Realizado'),(3,'Vencido'),(4,'Cancelado');

CREATE TABLE TIPO_CAPTURA (
  ID_TIPO_CAPTURA TINYINT NOT NULL CONSTRAINT PK_TIPO_CAPTURA PRIMARY KEY, -- 1 Tarea, 2 Idea, 3 Nota, 4 Cita, 5 Gasto, 6 Cobro, 7 Link, 8 Foto, 9 Archivo, 10 Código, 11 Audio
  NOMBRE          VARCHAR(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL);
INSERT INTO TIPO_CAPTURA VALUES
(1,'Tarea'),(2,'Idea'),(3,'Nota'),(4,'Cita'),(5,'Gasto'),(6,'Cobro'),(7,'Link'),(8,'Foto'),(9,'Archivo'),(10,'Código'),(11,'Audio');

CREATE TABLE ESTADO_TAREA (
  ID_ESTADO_TAREA TINYINT NOT NULL CONSTRAINT PK_ESTADO_TAREA PRIMARY KEY, -- 1 Backlog, 2 Siguiente, 3 Hoy, 4 EnCurso, 5 EnRevision, 6 Hecha, 7 Bloqueada
  NOMBRE          VARCHAR(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL);
INSERT INTO ESTADO_TAREA VALUES
(1,'Backlog'),(2,'Siguiente'),(3,'Hoy'),(4,'En curso'),(5,'En revisión'),(6,N'Hecha'),(7,N'Bloqueada');

CREATE TABLE CONTEXTO (
  ID_CONTEXTO TINYINT NOT NULL CONSTRAINT PK_CONTEXTO PRIMARY KEY, -- p.ej. 1 Oficina, 2 PC, 3 Tel�fono, 4 Casa
  NOMBRE      VARCHAR(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL);
INSERT INTO CONTEXTO VALUES
(1,N'Oficina'),(2,N'PC'),(3,N'Teléfono'),(4,N'Casa');
GO
/* ============================================
   USUARIOS Y PERSONAS (delegaci�n / familia)
   ============================================ */
CREATE TABLE USUARIO (
  ID_USUARIO  BIGINT           IDENTITY(1,1) CONSTRAINT PK_USUARIO PRIMARY KEY,
  UID         UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_USUARIO_UID DEFAULT NEWSEQUENTIALID() CONSTRAINT UQ_USUARIO_UID UNIQUE,
  NOMBRE      VARCHAR(120)     COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  EMAIL       VARCHAR(200)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  ROL         VARCHAR(40)      COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  ACTIVO      BIT              NOT NULL CONSTRAINT DF_USUARIO_ACTIVO DEFAULT(1),
  CREADO      DATETIME2(3)     NOT NULL CONSTRAINT DF_USUARIO_CREADO DEFAULT GETDATE(),
  MODIFICADO  DATETIME2(3)     NOT NULL CONSTRAINT DF_USUARIO_MODIFICADO DEFAULT GETDATE(),
  ROW_VERSION ROWVERSION);

CREATE TABLE PERSONA (
  ID_PERSONA  BIGINT           IDENTITY(1,1) CONSTRAINT PK_PERSONA PRIMARY KEY,
  UID         UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_PERSONA_UID DEFAULT NEWSEQUENTIALID() CONSTRAINT UQ_PERSONA_UID UNIQUE,
  ID_USUARIO  BIGINT           NULL CONSTRAINT FK_PERSONA_ID_USUARIO REFERENCES USUARIO(ID_USUARIO),
  NOMBRE      VARCHAR(120)     COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  RELACION    VARCHAR(60)      COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  EMAIL       VARCHAR(200)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  TELEFONO    VARCHAR(40)      COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  ACTIVO      BIT              NOT NULL CONSTRAINT DF_PERSONA_ACTIVO DEFAULT(1),
  notas       NVARCHAR(MAX)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  CREADO      DATETIME2(3)     NOT NULL CONSTRAINT DF_PERSONA_CREADO     DEFAULT GETDATE(),
  MODIFICADO  DATETIME2(3)     NOT NULL CONSTRAINT DF_PERSONA_MODIFICADO DEFAULT GETDATE(),
  ROW_VERSION ROWVERSION);
GO

/* ============================================
   PROYECTOS
   ============================================ */
CREATE TABLE PROYECTO (
  ID_PROYECTO   BIGINT           IDENTITY(1,1) CONSTRAINT PK_PROYECTO PRIMARY KEY,
  UID           UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_PROYECTO_UID DEFAULT NEWSEQUENTIALID() CONSTRAINT UQ_PROYECTO_UID UNIQUE,
  ID_USUARIO    BIGINT           NULL CONSTRAINT FK_PROYECTO_ID_USUARIO REFERENCES USUARIO(ID_USUARIO),
  NOMBRE        VARCHAR(200)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  OBJETIVO      VARCHAR(400)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  ID_AREA       TINYINT          NOT NULL CONSTRAINT FK_PROYECTO_ID_AREA REFERENCES AREAS(ID_AREA),
  ESTADO        VARCHAR(40)      COLLATE SQL_Latin1_General_CP1_CI_AS NULL, -- opcional (alto nivel)
  FEC_INICIO    DATE             NULL,
  FEC_FIN_PREVISTA DATE          NULL,
  PROGRESO_PCT  DECIMAL(5,2)     NULL CONSTRAINT CK_PROYECTO_PROGRESO_PCT CHECK (PROGRESO_PCT BETWEEN 0 AND 100),
  NOTAS_MD      NVARCHAR(MAX)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  CREADO        DATETIME2(3)     NOT NULL CONSTRAINT DF_PROYECTO_CREADO     DEFAULT GETDATE(),
  MODIFICADO    DATETIME2(3)     NOT NULL CONSTRAINT DF_PROYECTO_MODIFICADO DEFAULT GETDATE(),
  ROW_VERSION   ROWVERSION);
  
-- Etapas opcionales de proyecto (roadmap ligero)
CREATE TABLE PROYECTO_ETAPA (
  ID_ETAPA     BIGINT        IDENTITY(1,1) CONSTRAINT PK_PROYECTO_ETAPA PRIMARY KEY,
  ID_PROYECTO  BIGINT        NOT NULL CONSTRAINT FK_PROYECTO_ETAPA_ID_PROYECTO REFERENCES PROYECTO(ID_PROYECTO) ON DELETE CASCADE,
  NOMBRE       VARCHAR(120)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  ORDEN        INT           NOT NULL CONSTRAINT CK_PROYECTO_ETAPA_ORDEN CHECK (orden >= 0),
  DONE         BIT           NOT NULL CONSTRAINT DF_PROYECTO_ETAPA_DONE DEFAULT(0),
  CREADO       DATETIME2(3)  NOT NULL CONSTRAINT DF_PROYECTO_ETAPA_CREADO DEFAULT GETDATE(),
  MODIFICADO   DATETIME2(3)  NOT NULL CONSTRAINT DF_PROYECTO_ETAPA_MODIFICADO DEFAULT GETDATE());
GO
/* ============================================
   TAREAS
   ============================================ */
CREATE TABLE TAREA (
  ID_TAREA            BIGINT           IDENTITY(1,1) CONSTRAINT PK_TAREA PRIMARY KEY,
  UID                 UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_TAREA_UID DEFAULT NEWSEQUENTIALID() CONSTRAINT UQ_TAREA_UID UNIQUE,
  ID_USUARIO          BIGINT           NULL CONSTRAINT FK_TAREA_ID_USUARIO REFERENCES USUARIO(ID_USUARIO),
  ID_PROYECTO         BIGINT           NULL CONSTRAINT FK_TAREA_ID_PROYECTO REFERENCES PROYECTO(ID_PROYECTO) ON DELETE SET NULL,
  TITULO              VARCHAR(300)     COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  DETALLE_MD          NVARCHAR(MAX)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  ID_ESTADO_TAREA     TINYINT          NOT NULL CONSTRAINT FK_TAREA_ID_ESTADO_TAREA REFERENCES ESTADO_TAREA(ID_ESTADO_TAREA) DEFAULT(1),
  ID_AREA             TINYINT          NOT NULL CONSTRAINT DF_TAREA_ID_AREA DEFAULT(1) CONSTRAINT FK_TAREA_ID_AREA REFERENCES AREAS(ID_AREA),
  ID_CONTEXTO         TINYINT          NULL CONSTRAINT FK_TAREA_ID_CONTEXTO REFERENCES CONTEXTO(ID_CONTEXTO),
  ID_EISENHOWER       TINYINT          NULL CONSTRAINT FK_TAREA_ID_EISENHOWER REFERENCES EISENHOWER(ID_EISENHOWER),
  IMPACTO             TINYINT          NULL CONSTRAINT CK_TAREA_IMPACTO CHECK (impacto BETWEEN 1 AND 5),
  URGENTE_DIAS        TINYINT          NULL CONSTRAINT CK_TAREA_URGENTE_DIAS CHECK (urgente_dias BETWEEN 0 AND 31), -- bucket de urgencia
  FROG                BIT              NOT NULL CONSTRAINT DF_TAREA_FROG DEFAULT(0),
  PARETO              BIT              NOT NULL CONSTRAINT DF_TAREA_PARETO DEFAULT(0),
  BLOQUEADA           BIT              NOT NULL CONSTRAINT DF_TAREA_BLOQUEDA DEFAULT(0),
  BLOQUEO_MOTIVO      VARCHAR(300)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  DUE_DATE            DATETIME2(0)     NULL, -- permite hora si quieres
  SCORE               DECIMAL(9,4)     NOT NULL CONSTRAINT DF_TAREA_SCORE DEFAULT(0),
  SCORE_BOOST_UNTIL   DATETIME2(0)     NULL, -- +boost 24h si marcas �m�s urgente�
  RANKING             INT              NOT NULL CONSTRAINT DF_TAREA_RANKING DEFAULT(1000),
  POMOS_ESTIMADOS     TINYINT          NULL CONSTRAINT CK_TAREA_POMOS_ESTIMADOS CHECK (POMOS_ESTIMADOS BETWEEN 0 AND 200),
  POMOS_REALIZADOS    SMALLINT         NOT NULL CONSTRAINT DF_TAREA_POMOS_REALIZADOS DEFAULT(0) CONSTRAINT CK_TAREA_POMOS_REALIZADOS CHECK (POMOS_REALIZADOS >= 0),
  TIEMPO_TOTAL_MIN    INT              NOT NULL CONSTRAINT DF_TAREA_TIEMPO_TOTAL_MIN DEFAULT(0) CHECK (TIEMPO_TOTAL_MIN >= 0),
  ID_RESPONSABLE      BIGINT           NULL CONSTRAINT FK_TAREA_ID_RESPONSABLE REFERENCES PERSONA(ID_PERSONA),
  SEGUIMIENTO_PROXIMO DATE             NULL, -- Waiting For próximo ping
  CREADO              DATETIME2(3)     NOT NULL CONSTRAINT DF_TAREA_CREADO DEFAULT GETDATE(),
  MODIFICADO          DATETIME2(3)     NOT NULL CONSTRAINT DF_TAREA_MODIFICADO DEFAULT GETDATE(),
  ROW_VERSION         ROWVERSION);

CREATE INDEX IX_Tarea_Estado_Rank ON TAREA(ID_ESTADO_TAREA, RANKING);
CREATE INDEX IX_Tarea_Score_Due  ON TAREA(SCORE DESC, DUE_DATE);
CREATE INDEX IX_Tarea_Proyecto   ON TAREA(ID_PROYECTO) WHERE ID_ESTADO_TAREA <> 6; -- no Hecha
GO

/* Etiquetas genéricas */
CREATE TABLE ETIQUETA (
  ID_ETIQUETA BIGINT        IDENTITY(1,1) CONSTRAINT PK_ETIQUETA PRIMARY KEY,
  ID_USUARIO  BIGINT        NULL CONSTRAINT FK_ETIQUETA_ID_USUARIO REFERENCES USUARIO(ID_USUARIO),
  NOMBRE      VARCHAR(50)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  CONSTRAINT UQ_ETIQUETA_USUARIO_NOMBRE UNIQUE (ID_USUARIO, NOMBRE));

CREATE TABLE TAREA_ETIQUETA (
  ID_TAREA     BIGINT NOT NULL CONSTRAINT FK_TAREA_ETIQUETA_ID_TAREA REFERENCES TAREA(ID_TAREA) ON DELETE CASCADE,
  ID_ETIQUETA  BIGINT NOT NULL CONSTRAINT FK_TAREA_ETIQUETA_ID_ETIQUETA REFERENCES dbo.Etiqueta(ID_ETIQUETA) ON DELETE CASCADE,
  PRIMARY KEY (ID_TAREA, ID_ETIQUETA));
GO
/* ============================================
   HÁBITOS Y SESIONES (POMODORO/TIEMPO)
   ============================================ */
CREATE TABLE HABITO (
  ID_HABITO        BIGINT           IDENTITY(1,1) CONSTRAINT PK_HABITO PRIMARY KEY,
  UID              UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_HABITO_UID DEFAULT NEWSEQUENTIALID() CONSTRAINT UQ_HABITO_UID UNIQUE,
  ID_USUARIO       BIGINT           NULL CONSTRAINT FK_HABITO_ID_USUARIO REFERENCES USUARIO(ID_USUARIO),
  NOMBRE           VARCHAR(120)     COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  PERIODICIDAD     TINYINT          NOT NULL CONSTRAINT DF_HABITO_PERIODICIDAD DEFAULT(1), -- 1 diario, 2 semanal, 3 mensual (flexible)
  META             SMALLINT         NULL CONSTRAINT CK_HABITO_META CHECK (META >= 0), -- p.ej. #/semana
  CATEGORIA        VARCHAR(60)      COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  VISIBLE_FAMILIAR BIT              NOT NULL CONSTRAINT DF_HABITO_VISIBLE_FAMILIAR DEFAULT(0),
  STREAK           INT              NOT NULL CONSTRAINT DF_HABITO_STREAK DEFAULT(0),
  NOTAS            NVARCHAR(MAX)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  CREADO           DATETIME2(3)     NOT NULL CONSTRAINT DF_HABITO_CREADO DEFAULT GETDATE(),
  MODIFICADO       DATETIME2(3)     NOT NULL CONSTRAINT DF_HABITO_MODIFICADO DEFAULT GETDATE(),
  ROW_VERSION      ROWVERSION);

CREATE TABLE SESION_TRABAJO (
  ID_SESION        BIGINT           IDENTITY(1,1) CONSTRAINT PK_SESION_TRABAJO PRIMARY KEY,
  UID              UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_SESION_TRABAJO_UID DEFAULT NEWSEQUENTIALID() CONSTRAINT UQ_SESION_TRABAJO_UID UNIQUE,
  ID_USUARIO       BIGINT           NULL CONSTRAINT FK_SESION_TRABAJO_ID_USUARIO REFERENCES USUARIO(ID_USUARIO),
  ID_TAREA         BIGINT           NULL CONSTRAINT FK_SESION_TRABAJO_ID_TAREA REFERENCES TAREA(ID_TAREA) ON DELETE SET NULL,
  CATEGORIA        VARCHAR(60)      COLLATE SQL_Latin1_General_CP1_CI_AS NULL, -- p.ej. DeepWork, Soporte, Admin
  INICIO           DATETIME2(3)     NOT NULL,
  FIN              DATETIME2(3)     NULL,
  FOCO_MIN         SMALLINT         NOT NULL CONSTRAINT DF_SESION_TRABAJO_FOCO_MIN DEFAULT(0) CONSTRAINT CK_SESION_TRABAJO_FOCO_MIN CHECK (FOCO_MIN >= 0),
  DESCANSO_MIN     SMALLINT         NOT NULL CONSTRAINT DF_SESION_TRABAJO_DESCANSO_MIN DEFAULT(0) CONSTRAINT CK_SESION_TRABAJO_DESCANSO_MIN CHECK (DESCANSO_MIN >= 0),
  ID_MODO_ROLLOVER TINYINT          NOT NULL CONSTRAINT FK_SESION_TRABAJO_ID_MODO_ROLLOVER REFERENCES MODO_ROLLOVER(ID_MODO_ROLLOVER) DEFAULT(1),
  NOTAS            NVARCHAR(400)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  CREADO           DATETIME2(3)     NOT NULL DEFAULT GETDATE(),
  MODIFICADO       DATETIME2(3)     NOT NULL DEFAULT GETDATE());

CREATE INDEX IX_Sesion_Tarea_Inicio ON dbo.SESION_TRABAJO(ID_TAREA, INICIO DESC);
GO

/* ============================================
   DIARIO / REFLEXIVO
   ============================================ */
CREATE TABLE ENTRADA_DIARIO (
  ID_ENTRADA   BIGINT           IDENTITY(1,1) CONSTRAINT PK_ENTRADA_DIARIO PRIMARY KEY,
  UID          UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_ENTRADA_DIARIO_UID DEFAULT NEWSEQUENTIALID() CONSTRAINT UQ_ENTRADA_DIARIO_UID UNIQUE,
  ID_USUARIO   BIGINT           NULL CONSTRAINT FK_ENTRADA_DIARIO_ID_USUARIO REFERENCES USUARIO(ID_USUARIO),
  FECHA        DATE             NOT NULL CONSTRAINT DF_ENTRADA_DIARIO_FECHA DEFAULT CAST(GETDATE() AS DATE),
  CONTENIDO_MD NVARCHAR(MAX)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  CREADO       DATETIME2(3)     NOT NULL CONSTRAINT DF_ENTRADA_DIARIO_CREADO DEFAULT GETDATE(),
  MODIFICADO   DATETIME2(3)     NOT NULL CONSTRAINT DF_ENTRADA_DIARIO_MODIFICADO DEFAULT GETDATE());

CREATE TABLE ENTRADA_ETIQUETA (
  ID_ENTRADA  BIGINT NOT NULL CONSTRAINT FK_ENTRADA_ETIQUETA_ID_ENTRADA REFERENCES ENTRADA_DIARIO(ID_ENTRADA) ON DELETE CASCADE,
  ID_ETIQUETA BIGINT NOT NULL CONSTRAINT FK_ENTRADA_ETIQUETA_ID_ETIQUETA REFERENCES ETIQUETA(ID_ETIQUETA) ON DELETE CASCADE,
  PRIMARY KEY (ID_ENTRADA, ID_ETIQUETA));
GO

/* ============================================
   INBOX / CAPTURA
   ============================================ */
CREATE TABLE CAPTURA (
  ID_CAPTURA              BIGINT           IDENTITY(1,1) CONSTRAINT PK_CAPTURA PRIMARY KEY,
  UID                     UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_CAPTURA_UID DEFAULT NEWSEQUENTIALID() CONSTRAINT UQ_CAPTURA_UID UNIQUE,
  ID_USUARIO              BIGINT           NULL CONSTRAINT FK_CAPTURA_ID_USUARIO REFERENCES USUARIO(ID_USUARIO),
  ID_TIPO_CAPTURA         TINYINT          NOT NULL CONSTRAINT FK_CAPTURA_ID_TIPO_CAPTURA REFERENCES TIPO_CAPTURA(ID_TIPO_CAPTURA),
  TITULO                  VARCHAR(300)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  PAYLOAD_MD              NVARCHAR(MAX)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  METADATA_JSON           NVARCHAR(MAX)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL, -- libre (links, referencia rápida, etc.)
  ID_TAREA_RELACIONADO    BIGINT           NULL CONSTRAINT FK_CAPTURA_ID_TAREA_RELACIONADO REFERENCES TAREA(ID_TAREA) ON DELETE SET NULL,
  ID_PROYECTO_RELACIONADO BIGINT           NULL CONSTRAINT FK_CAPTURA_ID_PROYECTO_RELACIONADO REFERENCES PROYECTO(ID_PROYECTO) ON DELETE SET NULL,
  CREADO                  DATETIME2(3)     NOT NULL CONSTRAINT DF_CAPTURA_CREADO DEFAULT GETDATE());
GO

/* ============================================
   EVENTOS (calendario overlay)
   ============================================ */
CREATE TABLE EVENTO (
  ID_EVENTO      BIGINT           IDENTITY(1,1) CONSTRAINT PK_ID_EVENTO PRIMARY KEY,
  UID            UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_EVENTO_UID DEFAULT NEWSEQUENTIALID() CONSTRAINT UQ_EVENTO_UID UNIQUE,
  ID_USUARIO     BIGINT           NULL CONSTRAINT FK_EVENTO_ID_USUARIO REFERENCES USUARIO(ID_USUARIO),
  TITULO         VARCHAR(200)     COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  ID_TIPO_EVENTO TINYINT          NOT NULL CONSTRAINT FK_EVENTO_ID_TIPO_EVENTO REFERENCES TIPO_EVENTO(ID_TIPO_EVENTO),
  FECHA_INICIO   DATETIME2(0)     NOT NULL,
  FECHA_FIN      DATETIME2(0)     NULL,
  ALL_DAY        BIT              NOT NULL CONSTRAINT DF_EVENTO_ALL_DAY DEFAULT(0),
  UBICACION      VARCHAR(200)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  ID_PROYECTO    BIGINT           NULL CONSTRAINT FK_EVENTO_ID_PROYECTO REFERENCES PROYECTO(ID_PROYECTO) ON DELETE SET NULL,
  ID_TAREA       BIGINT           NULL CONSTRAINT FK_EVENTO_ID_TAREA REFERENCES TAREA(ID_TAREA) ON DELETE SET NULL,
  ID_PERSONA     BIGINT           NULL CONSTRAINT FK_EVENTO_ID_PERSONA REFERENCES PERSONA(ID_PERSONA) ON DELETE SET NULL, -- p.ej. cumpleaños
  NOTAS_MD       NVARCHAR(MAX)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  CREADO         DATETIME2(3)     NOT NULL CONSTRAINT DF_EVENTO_CREADO DEFAULT GETDATE(),
  MODIFICADO     DATETIME2(3)     NOT NULL CONSTRAINT DF_EVENTO_MODIFICADO DEFAULT GETDATE());
CREATE INDEX IX_Evento_Fecha ON dbo.Evento(fecha_inicio, fecha_fin);
GO
/* ============================================
   FINANZAS LITE
   ============================================ */
CREATE TABLE MOVTO_FINANCIERO (
  ID_MOV           BIGINT           IDENTITY(1,1) CONSTRAINT PK_MOVTO_FINANCIERO PRIMARY KEY,
  UID              UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_MOVTO_FINANCIERO_UID DEFAULT NEWSEQUENTIALID() CONSTRAINT UQ_MOVTO_FINANCIERO_UID UNIQUE,
  ID_USUARIO       BIGINT           NULL CONSTRAINT FK_MOVTO_FINANCIERO_ID_USUARIO REFERENCES USUARIO(ID_USUARIO),
  ID_TIPO_MOVTO    TINYINT          NOT NULL CONSTRAINT FK_MOVTO_FINANCIERO_ID_TIPO_MOVTO REFERENCES TIPO_MOVTO(ID_TIPO_MOVTO), -- Cobro/Pago
  CONTRAPARTE      VARCHAR(160)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  MONTO            DECIMAL(19,4)    NOT NULL CONSTRAINT CK_MOVTO_FINANCIERO_MONTO CHECK (MONTO >= 0),
  FECHA_OBJETIVO   DATE             NOT NULL,
  ID_STATUS_MOVTO  TINYINT          NOT NULL CONSTRAINT FK_MOVTO_FINANCIERO_ID_STATUS_MOVTO REFERENCES STATUS_MOVTO(ID_STATUS_MOVTO) DEFAULT(1),
  ID_PROYECTO      BIGINT           NULL CONSTRAINT FK_MOVTO_FINANCIERO_ID_PROYECTO REFERENCES PROYECTO(ID_PROYECTO) ON DELETE SET NULL,
  ID_TAREA         BIGINT           NULL CONSTRAINT FK_MOVTO_FINANCIERO_ID_TAREA REFERENCES TAREA(ID_TAREA) ON DELETE SET NULL,
  NOTAS_MD         NVARCHAR(MAX)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  CREADO           DATETIME2(3)     NOT NULL CONSTRAINT DF_MOVTO_FINANCIERO_CREADO DEFAULT GETDATE(),
  MODIFICADO       DATETIME2(3)     NOT NULL CONSTRAINT DF_MOVTO_FINANCIERO_MODIFICADO DEFAULT GETDATE());
CREATE INDEX IX_Mov_Fecha ON MOVTO_FINANCIERO(FECHA_OBJETIVO);
CREATE INDEX IX_Mov_Estatus ON MOVTO_FINANCIERO(ID_STATUS_MOVTO);
GO

/* ============================================
   ARCHIVOS (metadatos; contenido opcional)
   ============================================ */
CREATE TABLE ARCHIVO (
  ID_ARCHIVO    BIGINT           IDENTITY(1,1) CONSTRAINT PK_ARCHIVO PRIMARY KEY,
  UID           UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_ARCHIVO_UID DEFAULT NEWSEQUENTIALID() CONSTRAINT UQ_ARCHIVO_UID UNIQUE,
  ID_USUARIO    BIGINT           NULL CONSTRAINT FK_ARCHIVO_ID_USUARIO REFERENCES USUARIO(ID_USUARIO),
  TYPE_OWNER    VARCHAR(30)      NOT NULL, -- 'Tarea','Proyecto','Entrada','Movimiento','Evento','Captura','Habito'
  ID_OWNER      BIGINT           NOT NULL, -- PK del owner
  NOMBRE        VARCHAR(260)     COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, -- nombre archivo
  CONTENT_TYPE  VARCHAR(100)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  RUTA          VARCHAR(400)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,     -- path/URL cuando no guardas binario
  CONTENIDO     VARBINARY(MAX)   NULL,     -- opcional si decides guardar dentro (sin FILESTREAM)
  SHA256        VARBINARY(32)    NULL,
  TAMANO_BYTES  BIGINT           NULL,
  CREADO        DATETIME2(3)     NOT NULL CONSTRAINT DF_ARCHIVO_CREADO DEFAULT GETDATE());
CREATE INDEX IX_Archivo_Owner ON ARCHIVO(TYPE_OWNER, ID_OWNER);
GO
/* ============================================
   CONFIGURACIÓN (pesos, preferencias)
   ============================================ */
CREATE TABLE CONFIGURACION (
  ID_CONFIG   BIGINT           IDENTITY(1,1) CONSTRAINT PK_CONFIGURACION PRIMARY KEY,
  UID         UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_CONFIGURACION_UID DEFAULT NEWSEQUENTIALID() CONSTRAINT UQ_CONFIGURACION_UID UNIQUE,
  ID_USUARIO  BIGINT           NULL CONSTRAINT FK_CONFIGURACION_ID_USUARIO REFERENCES USUARIO(ID_USUARIO),
  CLAVE       VARCHAR(100)     COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,  -- ej: 'priority.weights', 'pomodoro.base', 'ui.theme'
  VALOR       VARCHAR(MAX)     COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,  -- JSON, texto o escalar en string
  CREADO      DATETIME2(3)     NOT NULL CONSTRAINT DF_CONFIGURACION_CREADO DEFAULT GETDATE(),
  MODIFICADO  DATETIME2(3)     NOT NULL CONSTRAINT DF_CONFIGURACION_MODIFICADO DEFAULT GETDATE(),
  CONSTRAINT UQ_CONFIGURACION_USUARIO_CLAVE UNIQUE (ID_USUARIO, CLAVE));
GO

/* ============================================
   INDICES SUGERIDOS ADICIONALES
   ============================================ */
-- Tareas abiertas (para listas r�pidas)
CREATE INDEX IX_Tarea_Abiertas ON TAREA(DUE_DATE, SCORE DESC) WHERE ID_ESTADO_TAREA <> 6; -- no Hecha
-- Finanzas radar pr�ximos 30 d�as
CREATE INDEX IX_Mov_Prox ON MOVTO_FINANCIERO(ID_STATUS_MOVTO, FECHA_OBJETIVO, ID_TIPO_MOVTO);
-- Diario por fecha
CREATE INDEX IX_EntradaDiario_Fecha ON ENTRADA_DIARIO(FECHA DESC);
